name:          "WTF, HTML and CSS?"
url:           http://wtfhtmlcss.com
repo:          https://github.com/lizheming/wtf-html-css
twitter:       https://twitter.com/mdo
translator:    http://zh.eming.li

markdown:      redcarpet
permalink:     pretty
pygments:      true
